version: '3'

services:
  web:
    restart: always
    build: .
    container_name: resturent_web
    volumes:
      - .:/web
    ports:
        - "8000:8000"
    command: bash -c "python3 manage.py makemigrations;python3 manage.py migrate;
                 python3 manage.py collectstatic --no-input;
                 python3 manage.py create_init_db;
                 gunicorn resturant_task.wsgi -b  0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: resturent_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=local
    volumes:
          - ./db:/docker-entrypoint-initdb.d/
    ports:
        - "5433:5432"


