# Generated by Django 3.2 on 2021-05-03 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_emp_number_user_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'employee number must be 4 characters long')]),
        ),
    ]
